server:
  port: 443
  servlet:
    context-path: /api
#  ssl:
#    key-store: classpath:server.jks
#    key-store-password: Ij1&IdQlkLXhR209
#    key-store-type: JKS

spring:
  datasource:
    url: jdbc:mysql://112.126.82.130:3306/sunhomo_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: sunhomo
    password: ironpearl
  redis:
    database: 1
    #单机版配置
    host: 112.126.82.130
    port: 6379
    password: ironpearl
    #集群配置
    #    cluster:
    #      max-redirects: 1
    #      nodes:
    #        - 127.0.0.1:7010
    #        - 127.0.0.1:7011
    #        - 127.0.0.1:7012
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
      timeout: 1000
      
mybatis:
  # 搜索指定包别名
  type-aliases-package: cn.sunhomo.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  config-location: classpath:mybatis/mybatis-config.xml

weiChat:
  miniProgram:
    appId: wx0cac0d85b62f2830
    appSecret: 1384a5076809cce29dd3de54675a6f8f