server:
  port: 80
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://124.70.145.232:3306/sunhomo_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: sunhomo
    password: ironpearl
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false

mybatis:
  # 搜索指定包别名
  type-aliases-package: cn.sunhomo.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  config-location: classpath:mybatis/mybatis-config.xml

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
